name: Unit Tests

on:
    pull_request:
        branches:
            - master

jobs:
    unit-test-81:
        name: Run PHPUnit on PHP 8.1 Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout the repository code
                uses: actions/checkout@v4
            -   name: Composer install
                uses: php-actions/composer@v6
                with:
                    php_version: 8.1
                    version: 2
                    dev: yes
            -   name: PHPUnit
                run: "./vendor/bin/phpunit"

    unit-test-82:
        name: Run PHPUnit on PHP 8.2 Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout the repository code
                uses: actions/checkout@v4
            -   name: Composer install
                uses: php-actions/composer@v6
                with:
                    php_version: 8.2
                    version: 2
                    dev: yes
            -   name: PHPUnit
                run: "./vendor/bin/phpunit"

    unit-test-83:
        name: Run PHPUnit on PHP 8.3 Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout the repository code
                uses: actions/checkout@v4
            -   name: Composer install
                uses: php-actions/composer@v6
                with:
                    php_version: 8.3
                    version: 2
                    dev: yes
            -   name: PHPUnit
                run: "./vendor/bin/phpunit"